### PR TITLE
allow passing a custom endpoint-url to boto3

### PR DESCRIPTION
**Pull request by MaZderMind**
We are Running an Flask-S3 enabled Application with a self-hosted Amazon S3 Compatible Storage-Client ([Minio](https://www.minio.io/)).

This PR adds the ability to configure a custom Endpoint-URL into the Boto-Client, so that it accesses the local instance. It defaults to None, which does maintain the existing behavior.

Please let me know if I should instead open a PR against [superdesk/superdesk-core](https://github.com/superdesk/superdesk-core), It should be easy to port this to the newer Version there.

### CODE REVIEW

**Comment by MaZderMind** [comment]
@nistormihai Hi, would you mind elaborating, why you closed this PR without a message? Are there any Problems I could try to fix?

**Comment by MaZderMind** [comment]
@nistormihai Can I interpret the Closing of this issue and the not responding from you as you not being interested in this feature? I wouldn't mind if this is the case, but it would be good style to just say that instead of closing a PR without a comment.

**Comment by mrs83** [comment]
@MaZderMind thanks for your contribution, It was probably closed as you were using  _liveblog/superdesk-core_ instead of _superdesk/superdesk-core_ fork.  It has been reported to the superdesk-core team.

**Comment by petrjasek** [comment]
@MaZderMind can you open it on superdesk/superdesk-core instead? thx

**Comment by MaZderMind** [comment]
@mscam @petrjasek Thank you very much for responding. Sure I'll migrate this PR to superdesk/superdesk-core.

I opened it on this Fork, because it is referenced in https://github.com/liveblog/liveblog/blob/master/server/requirements.txt#L78 and it seems that the liveblog-software is planned to be build with this fork.

Do you use the liveblog-Software with the most recent version of superdesk/superdesk-core? If so it might be good to update the liveblog's requirements-file to point there.

**Comment by mrs83** [comment]
@MaZderMind we recently made some changes, and we are currently using Superdesk 1.6 directly from superdesk-core main repository instead of using fork with cherry-picked changesets https://github.com/liveblog/liveblog/blob/devel/server/requirements.txt#L73

**Pull request closed without merging**
